SmarterRooms::Application.config.smarter_rooms_rooms_api_url = 'https://ca-3-api.mybluemix.net/'
SmarterRooms::Application.config.smarter_rooms_rooms_api_path = 'api/v1/rooms/'
SmarterRooms::Application.config.smarter_rooms_rooms_per_page = 6
SmarterRooms::Application.config.smarter_rooms_users_per_page = 5
SmarterRooms::Application.config.smarter_rooms_calendar_start_time = 9
SmarterRooms::Application.config.smarter_rooms_calendar_end_time = 18
SmarterRooms::Application.config.smarter_rooms_calendar_slot_duration = '00:15'
SmarterRooms::Application.config.smarter_rooms_calendar_hidden_days = '[0, 6]'
SmarterRooms::Application.config.smarter_rooms_calendar_max_results = 100
